[package]
name = "bevy_elements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
bevy_elements_macro = { path = "bevy_elements_macro" }
bevy_elements_core = { path = "bevy_elements_core" }
bevy_elements_widgets = { path = "bevy_elements_widgets" }
proc-macro2 = "1.0.47"
procout = { version = "0.1.13", features = ["procout"] }
bevy-inspector-egui = "0.13.0"
