[package]
name = "bevy_elements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "bevy_elements_core",
    "bevy_elements_macro",
    "bevy_elements_widgets",
    "tagstr",
    "tagstr_core",
    "tagstr_macro"
]

[dependencies]
bevy = "0.9.0"
bevy_elements_macro = { path = "bevy_elements_macro" }
bevy_elements_core = { path = "bevy_elements_core" }
bevy_elements_widgets = { path = "bevy_elements_widgets" }
