[package]
name = "belly_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustdoc-types = "0.19.0"
rustdoc-json = "0.8"
serde_json = "1.0"

[[bin]]
name = "belly"
path = "src/main.rs"